version: '3.9'

services:
  projectOSDB:
    image : mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD : 1234
      MYSQL_DATABASE :  OS
      MYSQL_USER: root02
      MYSQL_PASSWORD : 1234
    ports : 
      - "3306:3306"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/mydb.sql
    command: --default-authentication-plugin=mysql_native_password
    networks:
      - mynetwork
  api:
    build: ./backendOS/
    ports:
      - "3000:3000"
    depends_on:
      - projectOSDB
    environment:
      NODE_ENV : "production"
    networks:
      - mynetwork
  web:
    build: ./frontendOS/
    ports: 
      - "4173:4173"
    networks:
      - mynetwork
networks:
  mynetwork:
    driver: bridge